// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MyFitnessCoach.Models.EfModels;

public partial class FoodCalory
{
    public string CategoryName { get; set; }

    public string FoodName { get; set; }

    public decimal? Kcal { get; set; }
}