// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Project_MyFitnessCoach.Models.EfModels;

public partial class Instructor
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string ImageUrl { get; set; }

    public string Description { get; set; }

    public int HourWage { get; set; }

    public int CancelCount { get; set; }

    [NotMapped]
    public bool IsActive { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<Shift> Shifts { get; set; } = new List<Shift>();

    public virtual User User { get; set; }
}