// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoachDb.Models.EfModels;

public partial class Member
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public byte? Gender { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public double? Weight { get; set; }

    public double? Height { get; set; }

    public string ActivityLevel { get; set; }

    public string Target { get; set; }

    public double? Bmr { get; set; }

    public double? Tdee { get; set; }

    public string ImageUrl { get; set; }

    public int CancelCount { get; set; }

    public virtual ICollection<ProductOrder> ProductOrders { get; set; } = new List<ProductOrder>();

    public virtual User User { get; set; }

    public virtual UserWallet UserWallet { get; set; }
}