// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MyFitnessCoachDb.Models.EfModels;

public partial class MyFitnessCoachDBContext : DbContext
{
    public MyFitnessCoachDBContext(DbContextOptions<MyFitnessCoachDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Function> Functions { get; set; }

    public virtual DbSet<Instructor> Instructors { get; set; }

    public virtual DbSet<Member> Members { get; set; }

    public virtual DbSet<PointOrder> PointOrders { get; set; }

    public virtual DbSet<PointsRecordDetail> PointsRecordDetails { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductCategory> ProductCategories { get; set; }

    public virtual DbSet<ProductOrder> ProductOrders { get; set; }

    public virtual DbSet<ProductOrderDetail> ProductOrderDetails { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<RoleFunction> RoleFunctions { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserExternalLogin> UserExternalLogins { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<UserWallet> UserWallets { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Function>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Function__3214EC07AF677099");

            entity.Property(e => e.FunctionName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Instructor>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Instruct__3214EC0784FC3FA7");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.User).WithMany(p => p.Instructors)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Instructors_Users");
        });

        modelBuilder.Entity<Member>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Members__3214EC07E164ABD8");

            entity.Property(e => e.ActivityLevel).HasMaxLength(50);
            entity.Property(e => e.Bmr).HasColumnName("BMR");
            entity.Property(e => e.DateOfBirth).HasPrecision(0);
            entity.Property(e => e.ImageUrl).HasMaxLength(300);
            entity.Property(e => e.Target).HasMaxLength(50);
            entity.Property(e => e.Tdee).HasColumnName("TDEE");

            entity.HasOne(d => d.User).WithMany(p => p.Members)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Members_Users");
        });

        modelBuilder.Entity<PointOrder>(entity =>
        {
            entity.Property(e => e.DiscountedPrice).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.OriginalPrice).HasColumnType("decimal(18, 0)");
        });

        modelBuilder.Entity<PointsRecordDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_PointsRecords");

            entity.Property(e => e.CreateAt)
                .IsRequired()
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.MerchandiseCategory)
                .IsRequired()
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.PointAmount)
                .IsRequired()
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.ReserveOrderId)
                .IsRequired()
                .HasMaxLength(10)
                .IsFixedLength();

            entity.HasOne(d => d.PointOrder).WithMany(p => p.PointsRecordDetails)
                .HasForeignKey(d => d.PointOrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PointsRecordDetails_PointOrders");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.Property(e => e.Description).IsRequired();
            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.OriginalPrice).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 0)");

            entity.HasOne(d => d.Category).WithMany(p => p.Products)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Products_Products");
        });

        modelBuilder.Entity<ProductCategory>(entity =>
        {
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<ProductOrder>(entity =>
        {
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.DiscountAmount).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.Mobile)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.OriginalAmount).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.Receiver)
                .IsRequired()
                .HasMaxLength(30);

            entity.HasOne(d => d.Member).WithMany(p => p.ProductOrders)
                .HasForeignKey(d => d.MemberId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductOrders_Members");
        });

        modelBuilder.Entity<ProductOrderDetail>(entity =>
        {
            entity.Property(e => e.DiscountedPrice).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.ImageUrl)
                .HasMaxLength(300)
                .HasColumnName("ImageURL");
            entity.Property(e => e.Memo).HasMaxLength(50);
            entity.Property(e => e.ProductName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.SubTotal).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 0)");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductOrderDetails)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductOrderDetails_Products");

            entity.HasOne(d => d.ProductOrder).WithMany(p => p.ProductOrderDetails)
                .HasForeignKey(d => d.ProductOrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductOrderDetails_ProductOrders");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Roles__3214EC0704ABA546");

            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(30);
        });

        modelBuilder.Entity<RoleFunction>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RoleFunc__3214EC07FFD1286A");

            entity.HasIndex(e => new { e.RoleId, e.FunctionId }, "UQ_RoleFunctions").IsUnique();

            entity.HasOne(d => d.Function).WithMany(p => p.RoleFunctions)
                .HasForeignKey(d => d.FunctionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RoleFunctions_Function");

            entity.HasOne(d => d.Role).WithMany(p => p.RoleFunctions)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RoleFunctions_Role");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Users__3214EC07FD13645D");

            entity.HasIndex(e => e.Email, "UQ_Users_Email").IsUnique();

            entity.HasIndex(e => e.Account, "UX_Users_Account")
                .IsUnique()
                .HasFilter("([Account] IS NOT NULL)");

            entity.Property(e => e.Account).HasMaxLength(50);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.HashedPassword).HasMaxLength(256);
            entity.Property(e => e.Mobile)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.NewMemberConfirmCode)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.NewMemberConfirmCodeExpiry).HasPrecision(0);
            entity.Property(e => e.ResetPasswordConfirmCode)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ResetPasswordConfirmCodeExpiry).HasPrecision(0);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(30);
        });

        modelBuilder.Entity<UserExternalLogin>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserExte__3214EC070958BFD3");

            entity.Property(e => e.LoginProvider)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ProviderDisplayName).HasMaxLength(100);
            entity.Property(e => e.ProviderKey)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.User).WithMany(p => p.UserExternalLogins)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ExternalLogins_Users");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserRole__3214EC07F2100E8D");

            entity.HasIndex(e => new { e.UserId, e.RoleId }, "UQ_UserRoles").IsUnique();

            entity.HasOne(d => d.Role).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRoles_Role");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRoles_User");
        });

        modelBuilder.Entity<UserWallet>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserWall__3214EC073A62190E");

            entity.HasIndex(e => e.MemberId, "UQ_UserWallets_Member").IsUnique();

            entity.Property(e => e.CurrentBalance).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.LastUpdated)
                .HasPrecision(0)
                .HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Member).WithOne(p => p.UserWallet)
                .HasForeignKey<UserWallet>(d => d.MemberId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserWallets_Members");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}