// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Project_MyFitnessCoach.Models.EfModels;

public partial class MyFitnessCoachDbContext : DbContext
{
    public MyFitnessCoachDbContext(DbContextOptions<MyFitnessCoachDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Food> Foods { get; set; }
    public virtual DbSet<FoodCategory> FoodCategories { get; set; }
    public virtual DbSet<FoodRecord> FoodRecords { get; set; }
    public virtual DbSet<Function> Functions { get; set; }
    public virtual DbSet<Instructor> Instructors { get; set; }
    public virtual DbSet<Member> Members { get; set; }
    public virtual DbSet<Nutrient> Nutrients { get; set; }
    public virtual DbSet<PointOrder> PointOrders { get; set; }
    public virtual DbSet<PointsRecordDetail> PointsRecordDetails { get; set; }
    public virtual DbSet<Product> Products { get; set; }
    public virtual DbSet<ProductCategory> ProductCategories { get; set; }
    public virtual DbSet<ProductOrder> ProductOrders { get; set; }
    public virtual DbSet<ProductOrderDetail> ProductOrderDetails { get; set; }
    public virtual DbSet<Role> Roles { get; set; }
    public virtual DbSet<RoleFunction> RoleFunctions { get; set; }
    public virtual DbSet<TopUpPlan> TopUpPlans { get; set; }
    public virtual DbSet<User> Users { get; set; }
    public virtual DbSet<UserExternalLogin> UserExternalLogins { get; set; }
    public virtual DbSet<UserRole> UserRoles { get; set; }
    public virtual DbSet<UserWallet> UserWallets { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Food>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Foods__3214EC07A9C0B9E7");

            entity.Property(e => e.FoodName)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Category).WithMany(p => p.Foods)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Foods_FoodCategories");
        });

        modelBuilder.Entity<FoodCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FoodCate__3214EC07A4B4C182");

            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<FoodRecord>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FoodReco__3214EC07B3F1864B");

            entity.Property(e => e.EatDt)
                .HasPrecision(0)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("EatDT");

            entity.Property(e => e.MealType)
                .IsRequired()
                .HasMaxLength(20);

            entity.Property(e => e.Measure)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Food).WithMany(p => p.FoodRecords)
                .HasForeignKey(d => d.FoodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FoodRecords_Foods");

            entity.HasOne(d => d.Member).WithMany(p => p.FoodRecords)
                .HasForeignKey(d => d.MemberId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FoodRecords_Members");
        });

        modelBuilder.Entity<Function>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Function__3214EC07114E7B72");

            entity.Property(e => e.FunctionName)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.IsActive).HasDefaultValue(false);
        });

        modelBuilder.Entity<Instructor>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Instruct__3214EC07B9A14E26");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(500);

            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasMaxLength(300);

            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.User).WithMany(p => p.Instructors)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Instructors_Users");
        });

        modelBuilder.Entity<Member>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Members__3214EC079136E28E");

            entity.Property(e => e.ActivityLevel).HasMaxLength(50);
            entity.Property(e => e.Bmr).HasColumnName("BMR");
            entity.Property(e => e.DateOfBirth).HasPrecision(0);
            entity.Property(e => e.ImageUrl).HasMaxLength(300);
            entity.Property(e => e.Target).HasMaxLength(50);
            entity.Property(e => e.Tdee).HasColumnName("TDEE");

            entity.HasOne(d => d.User).WithMany(p => p.Members)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Members_Users");
        });

        modelBuilder.Entity<Nutrient>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Nutrient__3214EC0788DFB27B");

            entity.Property(e => e.Measure)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Food).WithMany(p => p.Nutrients)
                .HasForeignKey(d => d.FoodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Nutrients_Foods");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Products");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(e => e.ImageUrl).HasMaxLength(300);

            entity.Property(e => e.OriginalPrice).HasColumnType("decimal(18, 0)");

            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 0)");

            entity.HasOne(d => d.Category).WithMany(p => p.Products)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Products_ProductCategories");
        });

        modelBuilder.Entity<ProductCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_ProductCategories");

            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Roles__3214EC07E40304E0");

            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(30);

            entity.Property(e => e.IsActive).HasDefaultValue(false);
        });

        modelBuilder.Entity<RoleFunction>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RoleFunc__3214EC074F77D49C");

            entity.HasIndex(e => new { e.RoleId, e.FunctionId }, "UQ_RoleFunctions").IsUnique();

            entity.HasOne(d => d.Function).WithMany(p => p.RoleFunctions)
                .HasForeignKey(d => d.FunctionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RoleFunctions_Function");

            entity.HasOne(d => d.Role).WithMany(p => p.RoleFunctions)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RoleFunctions_Role");
        });

        modelBuilder.Entity<TopUpPlan>(entity =>
        {
            entity.Property(e => e.PlanName).HasMaxLength(50);
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Users__3214EC07DE5F3AE4");

            entity.HasIndex(e => e.Email, "UQ_Users_Email").IsUnique();

            entity.HasIndex(e => e.Account, "UX_Users_Account")
                .IsUnique()
                .HasFilter("([Account] IS NOT NULL)");

            entity.Property(e => e.Account).HasMaxLength(50);

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(200);

            entity.Property(e => e.HashedPassword).HasMaxLength(256);

            entity.Property(e => e.IsActive).HasDefaultValue(false);

            entity.Property(e => e.Mobile)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.NewMemberConfirmCode)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.NewMemberConfirmCodeExpiry).HasPrecision(0);

            entity.Property(e => e.ResetPasswordConfirmCode)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.ResetPasswordConfirmCodeExpiry).HasPrecision(0);

            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(30);
        });

        modelBuilder.Entity<UserExternalLogin>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserExte__3214EC070AAFF429");

            entity.Property(e => e.LoginProvider)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.ProviderDisplayName).HasMaxLength(100);

            entity.Property(e => e.ProviderKey)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.User).WithMany(p => p.UserExternalLogins)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ExternalLogins_Users");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserRole__3214EC07534211F7");

            entity.HasIndex(e => new { e.UserId, e.RoleId }, "UQ_UserRoles").IsUnique();

            entity.HasOne(d => d.Role).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRoles_Role");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRoles_User");
        });

        modelBuilder.Entity<UserWallet>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserWall__3214EC07336E0485");

            entity.HasIndex(e => e.MemberId, "UQ_UserWallets_Member").IsUnique();

            entity.Property(e => e.CurrentBalance).HasColumnType("decimal(10, 2)");

            entity.Property(e => e.LastUpdated)
                .HasPrecision(0)
                .HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Member).WithOne(p => p.UserWallet)
                .HasForeignKey<UserWallet>(d => d.MemberId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserWallets_Members");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}