// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MyFitnessCoach.Models.EfModels;

public partial class PointsRecordDetail
{
    public int Id { get; set; }

    public int PointOrderId { get; set; }

    public int UserWalletId { get; set; }

    public string CreateAt { get; set; }

    public string PointAmount { get; set; }

    public string MerchandiseCategory { get; set; }

    public string ReserveOrderId { get; set; }

    public virtual PointOrder PointOrder { get; set; }
}