// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Project_MyFitnessCoach.Models.EfModels;

public partial class ResRevContext : DbContext
{
    public ResRevContext(DbContextOptions<ResRevContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Food> Foods { get; set; }

    public virtual DbSet<FoodCategory> FoodCategories { get; set; }

    public virtual DbSet<FoodRecord> FoodRecords { get; set; }

    public virtual DbSet<Function> Functions { get; set; }

    public virtual DbSet<Instructor> Instructors { get; set; }

    public virtual DbSet<Member> Members { get; set; }

    public virtual DbSet<Nutrient> Nutrients { get; set; }

    public virtual DbSet<ReserveOrder> ReserveOrders { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<RoleFunction> RoleFunctions { get; set; }

    public virtual DbSet<SensitiveWord> SensitiveWords { get; set; }

    public virtual DbSet<Shift> Shifts { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserExternalLogin> UserExternalLogins { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<UserWallet> UserWallets { get; set; }

    public virtual DbSet<VwUserMemberFoodRecord> VwUserMemberFoodRecords { get; set; }

    public virtual DbSet<VwUserRoleFunction> VwUserRoleFunctions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Food>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Foods__3214EC07BB6449E5");

            entity.Property(e => e.FoodName)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Category).WithMany(p => p.Foods)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Foods_FoodCategories");
        });

        modelBuilder.Entity<FoodCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FoodCate__3214EC073D7148AA");

            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<FoodRecord>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FoodReco__3214EC076B3150DF");

            entity.Property(e => e.EatDt)
                .HasPrecision(0)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("EatDT");
            entity.Property(e => e.MealType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Measure)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Food).WithMany(p => p.FoodRecords)
                .HasForeignKey(d => d.FoodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FoodRecords_Foods");

            entity.HasOne(d => d.Member).WithMany(p => p.FoodRecords)
                .HasForeignKey(d => d.MemberId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FoodRecords_Members");
        });

        modelBuilder.Entity<Function>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Function__3214EC0771FD9711");

            entity.Property(e => e.FunctionName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Instructor>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Instruct__3214EC07D5682AF7");

            entity.Property(e => e.CancelCount).HasDefaultValue(1);
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.User).WithMany(p => p.Instructors)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Instructors_Users");
        });

        modelBuilder.Entity<Member>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Members__3214EC07C34D1382");

            entity.Property(e => e.ActivityLevel).HasMaxLength(50);
            entity.Property(e => e.Bmr).HasColumnName("BMR");
            entity.Property(e => e.CancelCount).HasDefaultValue(1);
            entity.Property(e => e.DateOfBirth).HasPrecision(0);
            entity.Property(e => e.ImageUrl).HasMaxLength(300);
            entity.Property(e => e.Target).HasMaxLength(50);
            entity.Property(e => e.Tdee).HasColumnName("TDEE");

            entity.HasOne(d => d.User).WithMany(p => p.Members)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Members_Users");
        });

        modelBuilder.Entity<Nutrient>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Nutrient__3214EC07EF3700C1");

            entity.Property(e => e.Measure)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Food).WithMany(p => p.Nutrients)
                .HasForeignKey(d => d.FoodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Nutrients_Foods");
        });

        modelBuilder.Entity<ReserveOrder>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ReserveO__3214EC0779CA509B");

            entity.Property(e => e.CreateAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Memorandum).HasMaxLength(100);
            entity.Property(e => e.PaymentMethod)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.Target).HasMaxLength(300);

            entity.HasOne(d => d.Member).WithMany(p => p.ReserveOrders)
                .HasForeignKey(d => d.MemberId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReserveOrders_Members");

            entity.HasOne(d => d.Shift).WithMany(p => p.ReserveOrders)
                .HasForeignKey(d => d.ShiftId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReserveOrders_Shifts");
        });

        modelBuilder.Entity<Review>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Reviews__3214EC07C7FF0B28");

            entity.Property(e => e.Comment).HasMaxLength(500);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Instructor).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.InstructorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Reviews_Instructors");

            entity.HasOne(d => d.Member).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.MemberId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Reviews_Members");

            entity.HasOne(d => d.ReserveOrder).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.ReserveOrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Reviews_ReserveOrders");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Roles__3214EC075C4CBFEA");

            entity.HasIndex(e => e.RoleName, "UQ__Roles__8A2B6160DB202A09").IsUnique();

            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(30);
        });

        modelBuilder.Entity<RoleFunction>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RoleFunc__3214EC07E7223C21");

            entity.HasIndex(e => new { e.RoleId, e.FunctionId }, "UQ_RoleFunctions").IsUnique();

            entity.HasOne(d => d.Function).WithMany(p => p.RoleFunctions)
                .HasForeignKey(d => d.FunctionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RoleFunctions_Function");

            entity.HasOne(d => d.Role).WithMany(p => p.RoleFunctions)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RoleFunctions_Role");
        });

        modelBuilder.Entity<SensitiveWord>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Sensitiv__3214EC0788FDD38C");

            entity.HasIndex(e => e.Word, "UQ__Sensitiv__95B5010825CB51BA").IsUnique();

            entity.Property(e => e.Word)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Review).WithMany(p => p.SensitiveWords)
                .HasForeignKey(d => d.ReviewId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SensitiveWords_Reviews");
        });

        modelBuilder.Entity<Shift>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Shifts__3214EC079869BD50");

            entity.HasIndex(e => new { e.InstructorId, e.ScheduleDate, e.TimeSlot }, "UQ_Instructor_Shift").IsUnique();

            entity.Property(e => e.TimeSlot)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Instructor).WithMany(p => p.Shifts)
                .HasForeignKey(d => d.InstructorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Shifts_Instructors");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Users__3214EC07D7B5C8CE");

            entity.HasIndex(e => e.Email, "UQ_Users_Email").IsUnique();

            entity.HasIndex(e => e.Account, "UX_Users_Account")
                .IsUnique()
                .HasFilter("([Account] IS NOT NULL)");

            entity.Property(e => e.Account).HasMaxLength(50);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Password).HasMaxLength(256);
            entity.Property(e => e.Mobile)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.NewMemberConfirmCode)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.NewMemberConfirmCodeExpiry).HasPrecision(0);
            entity.Property(e => e.ResetPasswordConfirmCode)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ResetPasswordConfirmCodeExpiry).HasPrecision(0);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(30);
        });

        modelBuilder.Entity<UserExternalLogin>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserExte__3214EC07BCC9AE74");

            entity.Property(e => e.LoginProvider)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ProviderDisplayName).HasMaxLength(100);
            entity.Property(e => e.ProviderKey)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.User).WithMany(p => p.UserExternalLogins)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ExternalLogins_Users");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserRole__3214EC074EDCD156");

            entity.HasIndex(e => new { e.UserId, e.RoleId }, "UQ_UserRoles").IsUnique();

            entity.HasOne(d => d.Role).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRoles_Role");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRoles_User");
        });

        modelBuilder.Entity<UserWallet>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserWall__3214EC0726B620F0");

            entity.HasIndex(e => e.MemberId, "UQ_UserWallets_Member").IsUnique();

            entity.Property(e => e.LastUpdated)
                .HasPrecision(0)
                .HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Member).WithOne(p => p.UserWallet)
                .HasForeignKey<UserWallet>(d => d.MemberId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserWallets_Members");
        });

        modelBuilder.Entity<VwUserMemberFoodRecord>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_UserMemberFoodRecord");

            entity.Property(e => e.Bmr).HasColumnName("BMR");
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.EatDt)
                .HasPrecision(0)
                .HasColumnName("EatDT");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.FoodName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.MealType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.NutrientMeasure).HasMaxLength(20);
            entity.Property(e => e.RecordMeasure)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Tdee).HasColumnName("TDEE");
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(30);
        });

        modelBuilder.Entity<VwUserRoleFunction>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_UserRoleFunction");

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.FunctionName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(30);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}