// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MyFitnessCoach.Models.EfModels;

public partial class SensitiveWord
{
    public int Id { get; set; }

    public int ReviewId { get; set; }

    public string Word { get; set; }

    public virtual Review Review { get; set; }
}