// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Project_MyFitnessCoach.Models.EfModels;

public partial class User
{
    public int Id { get; set; }

    public string Account { get; set; }

    public string Password { get; set; }

    public string UserName { get; set; }

    public string Email { get; set; }

    [NotMapped]
    public string Mobile { get; set; }

    [NotMapped]
    public bool IsConfirmed { get; set; }

    [NotMapped]
    public bool IsActive { get; set; }

    [NotMapped]
    public string NewMemberConfirmCode { get; set; }

    [NotMapped]
    public DateTime? NewMemberConfirmCodeExpiry { get; set; }

    [NotMapped]
    public string ResetPasswordConfirmCode { get; set; }

    [NotMapped]
    public DateTime? ResetPasswordConfirmCodeExpiry { get; set; }

    public virtual ICollection<Instructor> Instructors { get; set; } = new List<Instructor>();

    public virtual ICollection<Member> Members { get; set; } = new List<Member>();

    public virtual ICollection<UserExternalLogin> UserExternalLogins { get; set; } = new List<UserExternalLogin>();

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}