// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoachDb.Models.EfModels;

public partial class UserWallet
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public decimal CurrentBalance { get; set; }

    public DateTime LastUpdated { get; set; }

    public virtual Member Member { get; set; }
}