// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MyFitnessCoach.Models.EfModels;

public partial class VwUserRoleFunction1
{
    public string UserName { get; set; }

    public string Account { get; set; }

    public string RoleName { get; set; }

    public string FunctionName { get; set; }
}