// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_MyFitnessCoach.Models.EfModels;

public partial class VwUserMemberFoodRecord
{
    public int UserId { get; set; }

    public string UserName { get; set; }

    public string Email { get; set; }

    public int MemberId { get; set; }

    public bool? Gender { get; set; }

    public double? Weight { get; set; }

    public double? Height { get; set; }

    public double? Bmr { get; set; }

    public double? Tdee { get; set; }

    public int FoodRecordId { get; set; }

    public DateTime EatDt { get; set; }

    public string MealType { get; set; }

    public double Amount { get; set; }

    public string RecordMeasure { get; set; }

    public int FoodId { get; set; }

    public string FoodName { get; set; }

    public string CategoryName { get; set; }

    public int? BaseAmount { get; set; }

    public string NutrientMeasure { get; set; }

    public double? TotalKcal { get; set; }

    public double? TotalProtein { get; set; }

    public double? TotalCarb { get; set; }

    public double? TotalFat { get; set; }
}